luiscarlossf/how-to-contribute

- hacktoberfest1/hacktoberfest.java
- hacktoberfest1/info.txt
Just someone to get it outta the way today. Just don't have the time.
> first commit

- code/Assembly-prime/algoritmo.s
Hi, its a assembly code for cheking prime numbers, the entry and exit are writen in the memorie, 👍
> Add assembly code for cheking prime numbers

- code/caesar decrypt.py
Implementation in python to decrypt an encrypted message with Caesar
> Caesar decrypt

- code/big_factorial/Readme.md
- code/big_factorial/using_array.cpp
- code/big_factorial/using_gmp.cpp
Perform big factorial in C++ using:
* GNU GMP (CXX)
* Array
> Added 2 ways to perform big factorial in C++

- hello_world_go/hellor_world.go
> Hello World in Go

- code/AtividadeDia02 (1).c
i did some changes in your repository! please, check out!
> It's a code! #2

- code/getDay.js
> Added js switch example

- README.md
> Updated readme with images

- code/edit_distance.cpp
Added C++ code for edit_distance
> Added edit_distance.cpp

- code/binary_search.cpp
> Added Binary Search Algorithm using CPP

- code/kotlin/BubbleSort.kt
contributing to https://github.com/luiscarlossf/how-to-contribute/issues/2
> Create bubble sort in kotlin

- code/python/prime_number_in_range.py
This program finds the prime numbers between two numbers. Both the numbers are included.
> prime_number_in_range.py

- code/cpp/bst.cc
Implemented Binary Search Tree in C++. You can add, remove and print data
> BST in C++11

- code/php/get-day.php
adding php folder and php code to get day and display day.
> add php code to get day.

- code/cpp/merge_sort.cpp
> Created merge_sort.cpp

- code/cpp/selection_sort.cpp
> add selection sort in c++

- code/java/prime.java
- code/java/swap.java
Added codes for Prime no & Swapping values of two variables without using third variable
> Added new programs

- code/cpp/quick_sort.cpp
It's not the randomized algorithm and assumes the last element to be the pivot during partition subroutine.
> Add quick sort cpp algorithm implementation

- beautiful.json
I added an archive in JASON to make your repository more beautiful!
> add beautiful.json

- code/c/bubblesort.c
- code/python/bubblesort.py
- code/python/heapsort.py
- code/python/hibrido.py
- code/python/insertionsort.py
- code/python/mergesort.py
- code/python/quicksort.py
bubblesort with random numbers in c.
> Add bubble sort
